// The Dart half of the canvas display-list contract.
//
// The fixtures here are hand-written bytes, not bytes produced by this
// package: the whole point is to catch the JS writer and this decoder
// drifting apart, and a fixture generated by one of them could not do that.
// canvas-context.test.ts on the JS side asserts the same layouts.
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/painting.dart';
import 'package:flutter_fjs/src/canvas/canvas_ops.dart';
import 'package:flutter_fjs/src/canvas/display_list.dart';
import 'package:flutter_fjs/src/canvas/replay.dart';
import 'package:flutter_test/flutter_test.dart';

/// Builds a command chunk the way the JS writer does.
class _Chunk {
  final BytesBuilder _b = BytesBuilder();
  int _nextString = 1;

  int str(String value) {
    final id = _nextString++;
    final bytes = Uint8List.fromList(value.codeUnits);
    _b.addByte(CanvasCmd.strDef);
    _u16(id);
    _u16(bytes.length);
    _b.add(bytes);
    return id;
  }

  void cmd(int c) => _b.addByte(c);

  void u8(int v) => _b.addByte(v);

  void _u16(int v) {
    _b.addByte(v & 0xff);
    _b.addByte((v >> 8) & 0xff);
  }

  void u16(int v) => _u16(v);

  void u32(int v) {
    _b.addByte(v & 0xff);
    _b.addByte((v >> 8) & 0xff);
    _b.addByte((v >> 16) & 0xff);
    _b.addByte((v >> 24) & 0xff);
  }

  void f32(double v) {
    final bytes = ByteData(4)..setFloat32(0, v, Endian.little);
    _b.add(bytes.buffer.asUint8List());
  }

  Uint8List take() => _b.toBytes();
}

/// Records what the replay asked the canvas to do. A golden image would be
/// the other option, but it would also be a font-rendering test — and the
/// two platforms cannot agree on glyph metrics to the pixel (spec §4.1).
class _RecordingCanvas implements Canvas {
  final List<String> calls = [];
  final List<Paint> paints = [];

  @override
  void drawRect(Rect rect, Paint paint) {
    calls.add(
      'drawRect(${rect.left},${rect.top},${rect.width},${rect.height})',
    );
    paints.add(paint);
  }

  @override
  void drawPath(Path path, Paint paint) {
    final b = path.getBounds();
    calls.add('drawPath(${b.left},${b.top},${b.width},${b.height})');
    paints.add(paint);
  }

  @override
  void save() => calls.add('save');

  @override
  void restore() => calls.add('restore');

  @override
  void saveLayer(Rect? bounds, Paint paint) {
    calls.add('saveLayer(${paint.blendMode})');
  }

  @override
  void translate(double dx, double dy) => calls.add('translate($dx,$dy)');

  @override
  void transform(Float64List matrix4) => calls.add(
    'transform(${matrix4[0]},${matrix4[5]},${matrix4[12]},${matrix4[13]})',
  );

  @override
  void clipRect(
    Rect rect, {
    ui.ClipOp clipOp = ui.ClipOp.intersect,
    bool doAntiAlias = true,
  }) {
    calls.add('clipRect');
  }

  @override
  void clipPath(Path path, {bool doAntiAlias = true}) => calls.add('clipPath');

  @override
  void scale(double sx, [double? sy]) => calls.add('scale($sx,${sy ?? sx})');

  // Everything else is unused by these fixtures; failing loudly beats
  // silently accepting a command this test does not actually check.
  @override
  dynamic noSuchMethod(Invocation invocation) {
    calls.add('UNEXPECTED ${invocation.memberName}');
    return null;
  }
}

void main() {
  test('a fill is decoded into one rect with the interned colour', () {
    final chunk = _Chunk();
    final color = chunk.str('#07c160');
    chunk.cmd(CanvasCmd.setFillColor);
    chunk.u16(color);
    chunk.cmd(CanvasCmd.fillRect);
    chunk.f32(10);
    chunk.f32(20);
    chunk.f32(30);
    chunk.f32(40);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    expect(canvas.calls, ['drawRect(10.0,20.0,30.0,40.0)']);
    // toARGB32(): since Flutter 3.27 Color holds float components, and a
    // Paint's colour comes back through that conversion — comparing Color
    // objects fails on the float round-trip even when the ARGB is identical.
    expect(canvas.paints.single.color.toARGB32(), 0xFF07C160);
    expect(canvas.paints.single.style, PaintingStyle.fill);
  });

  test('a stroke carries width, cap and join', () {
    final chunk = _Chunk();
    chunk.cmd(CanvasCmd.setLineWidth);
    chunk.f32(4);
    chunk.cmd(CanvasCmd.setLineCap);
    chunk.u8(1); // round
    chunk.cmd(CanvasCmd.setLineJoin);
    chunk.u8(2); // bevel
    chunk.cmd(CanvasCmd.strokeRect);
    chunk.f32(0);
    chunk.f32(0);
    chunk.f32(10);
    chunk.f32(10);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    final paint = canvas.paints.single;
    expect(paint.style, PaintingStyle.stroke);
    expect(paint.strokeWidth, 4);
    expect(paint.strokeCap, StrokeCap.round);
    expect(paint.strokeJoin, StrokeJoin.bevel);
  });

  test('a path sub-stream becomes a Path with the right bounds', () {
    final path = _Chunk();
    path.cmd(CanvasPathCmd.moveTo);
    path.f32(10);
    path.f32(10);
    path.cmd(CanvasPathCmd.lineTo);
    path.f32(40);
    path.f32(50);
    path.cmd(CanvasPathCmd.close);
    final pathBytes = path.take();

    final chunk = _Chunk();
    chunk.cmd(CanvasCmd.fillPath);
    chunk.u8(0); // nonzero
    chunk.u32(pathBytes.length);
    chunk._b.add(pathBytes);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    expect(canvas.calls, ['drawPath(10.0,10.0,30.0,40.0)']);
  });

  test('a full-turn arc becomes a circle, not an empty path', () {
    // `ctx.arc(x, y, r, 0, Math.PI * 2)` is how every page draws a circle,
    // and Skia treats an arc whose start and end angles coincide as EMPTY —
    // so this is the difference between a filled dot and nothing at all.
    final path = _Chunk();
    path.cmd(CanvasPathCmd.arc);
    path.f32(210);
    path.f32(48);
    path.f32(32);
    path.f32(0);
    path.f32(6.283185307179586);
    path.u8(0);
    final pathBytes = path.take();

    final chunk = _Chunk();
    chunk.cmd(CanvasCmd.fillPath);
    chunk.u8(0);
    chunk.u32(pathBytes.length);
    chunk._b.add(pathBytes);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    expect(canvas.calls, ['drawPath(178.0,16.0,64.0,64.0)']);
  });

  test('a shadow draws the shape twice, the first time offset and blurred', () {
    final chunk = _Chunk();
    final shadow = chunk.str('rgba(0, 0, 0, 0.5)');
    chunk.cmd(CanvasCmd.setShadow);
    chunk.u16(shadow);
    chunk.f32(8); // blur
    chunk.f32(2); // dx
    chunk.f32(3); // dy
    chunk.cmd(CanvasCmd.fillRect);
    chunk.f32(0);
    chunk.f32(0);
    chunk.f32(10);
    chunk.f32(10);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    expect(canvas.calls, [
      'save',
      'translate(2.0,3.0)',
      'drawRect(0.0,0.0,10.0,10.0)',
      'restore',
      'drawRect(0.0,0.0,10.0,10.0)',
    ]);
    expect(canvas.paints.first.maskFilter, isNotNull);
    expect(canvas.paints.last.maskFilter, isNull);
  });

  test('a non-default composite mode is wrapped in a layer', () {
    final chunk = _Chunk();
    chunk.cmd(CanvasCmd.setComposite);
    chunk.u8(6); // destination-out
    chunk.cmd(CanvasCmd.fillRect);
    chunk.f32(0);
    chunk.f32(0);
    chunk.f32(4);
    chunk.f32(4);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(10, 10)).run([chunk.take()]);

    expect(canvas.calls.first, 'saveLayer(BlendMode.dstOut)');
    expect(canvas.calls.last, 'restore');
  });

  test('an unknown command throws instead of painting on', () {
    final chunk = _Chunk();
    chunk.cmd(0xEE);

    expect(
      () => CanvasReplay(
        _RecordingCanvas(),
        const Size(10, 10),
      ).run([chunk.take()]),
      throwsA(isA<CanvasOpException>()),
    );
  });

  test('a truncated chunk throws rather than reading past the end', () {
    final chunk = _Chunk();
    chunk.cmd(CanvasCmd.fillRect);
    chunk.f32(1); // three arguments short

    expect(
      () => CanvasReplay(
        _RecordingCanvas(),
        const Size(10, 10),
      ).run([chunk.take()]),
      throwsA(isA<CanvasOpException>()),
    );
  });

  test('transparent is a colour, not a parse failure', () {
    // A canvas assigns `fillStyle = 'transparent'` to mean "paint nothing".
    // Falling back to the default (opaque black) instead painted ECharts'
    // legend as two black boxes.
    final chunk = _Chunk();
    final color = chunk.str('transparent');
    chunk.cmd(CanvasCmd.setFillColor);
    chunk.u16(color);
    chunk.cmd(CanvasCmd.fillRect);
    chunk.f32(0);
    chunk.f32(0);
    chunk.f32(10);
    chunk.f32(10);

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(100, 100)).run([chunk.take()]);

    expect((canvas.paints.single.color.a * 255.0).round(), 0);
  });

  test('setTransform after a restore is measured from the restored matrix', () {
    // The shape ECharts draws every frame: translate into the plot area,
    // save, clip, draw the series, restore, then place the legend with a
    // fresh setTransform. The tracker that turns an absolute setTransform
    // into a Canvas-relative one has to be restored along with the canvas —
    // when it was not, the legend was transformed by the leftover matrix and
    // disappeared off the canvas.
    final chunk = _Chunk();
    void setTransform(double a, double d, double e, double f) {
      chunk.cmd(CanvasCmd.setTransform);
      for (final v in [a, 0.0, 0.0, d, e, f]) {
        chunk.f32(v);
      }
    }

    setTransform(1, 1, 40, 20); // into the plot area
    chunk.cmd(CanvasCmd.save);
    setTransform(2, 2, 0, 0); // something the series did
    chunk.cmd(CanvasCmd.restore);
    setTransform(1, 1, 40, 20); // the legend, back at the outer matrix

    final canvas = _RecordingCanvas();
    CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]);

    // the last transform must be a no-op: the canvas is already at (40, 20)
    // after the restore, so asking for (40, 20) again may not move it
    final last = canvas.calls.last;
    expect(
      last,
      'transform(1.0,1.0,0.0,0.0)',
      reason: 'delta computed against the restored matrix, not the stale one',
    );
  });

  group('retention', () {
    test('a chunk opening with CLEAR_ALL drops what came before it', () {
      final list = FjsCanvasDisplayList();
      final first = _Chunk()..cmd(CanvasCmd.save);
      list.append(first.take());
      expect(list.chunks, hasLength(1));

      final cleared = _Chunk()..cmd(CanvasCmd.clearAll);
      list.append(cleared.take());
      expect(list.chunks, hasLength(1), reason: 'the older chunk is gone');
    });

    test('a chunk that does not clear is appended', () {
      final list = FjsCanvasDisplayList();
      list.append((_Chunk()..cmd(CanvasCmd.save)).take());
      list.append((_Chunk()..cmd(CanvasCmd.save)).take());
      expect(list.chunks, hasLength(2));
    });

    test('the version changes so the painter repaints', () {
      final list = FjsCanvasDisplayList();
      final before = list.version;
      list.append((_Chunk()..cmd(CanvasCmd.save)).take());
      expect(list.version, isNot(before));
    });

    test('a NEEDS_LAYER head puts the canvas on its own layer', () {
      final list = FjsCanvasDisplayList();
      list.append((_Chunk()..cmd(CanvasCmd.save)).take());
      expect(list.needsLayer, isFalse);

      final partial = _Chunk()
        ..cmd(CanvasCmd.needsLayer)
        ..cmd(CanvasCmd.clearRect)
        ..f32(0)
        ..f32(0)
        ..f32(10)
        ..f32(10);
      list.append(partial.take());
      expect(list.needsLayer, isTrue);
    });

    test('NEEDS_LAYER survives the truncation it rides in front of', () {
      final list = FjsCanvasDisplayList();
      final marked = _Chunk()
        ..cmd(CanvasCmd.needsLayer)
        ..cmd(CanvasCmd.clearAll);
      list.append(marked.take());
      expect(list.chunks, hasLength(1));
      expect(
        list.needsLayer,
        isTrue,
        reason: 'the flag is read before the drop, not lost with it',
      );
    });

    test('the marker replays as a no-op', () {
      final chunk = _Chunk()
        ..cmd(CanvasCmd.needsLayer)
        ..cmd(CanvasCmd.clearRect)
        ..f32(0)
        ..f32(0)
        ..f32(10)
        ..f32(10);
      final canvas = _RecordingCanvas();
      expect(
        () => CanvasReplay(canvas, const Size(300, 200)).run([chunk.take()]),
        returnsNormally,
      );
    });

    test('a page that never clears the whole canvas is warned once', () {
      final list = FjsCanvasDisplayList();
      final logs = <String>[];
      // 241 frames that each clear only their own dirty rectangle: nothing
      // is ever dropped, so every repaint replays all of them
      final printed = () {
        for (var i = 0; i < 241; i++) {
          list.append(
            (_Chunk()
                  ..cmd(CanvasCmd.needsLayer)
                  ..cmd(CanvasCmd.save))
                .take(),
          );
        }
      };
      runZoned(
        printed,
        zoneSpecification: ZoneSpecification(
          print: (_, __, ___, line) => logs.add(line),
        ),
      );
      expect(logs, hasLength(1));
      expect(logs.single, contains('without a full-canvas clearRect()'));
    });

    test('clear() drops everything, as a resize does', () {
      final list = FjsCanvasDisplayList();
      list.append((_Chunk()..cmd(CanvasCmd.save)).take());
      list.clear();
      expect(list.isEmpty, isTrue);
      expect(list.needsLayer, isFalse);
    });
  });
}
