// fjs splash — regenerate the launch screens from one source PNG.
//
// Three mechanisms, three shapes:
//   Android <12      drawable*/launch_background.xml becomes a layer-list:
//                    one colour, one centred `launch_image` bitmap — the
//                    densities get their own drawable-<dpi> copy
//   Android 12+      the system splash: values-v31/styles.xml gets
//                    windowSplashScreenBackground + AnimatedIcon. The OS
//                    masks the icon to a circle at roughly 2/3 of the
//                    screen area — that is policy, not a file we control,
//                    so the command says so once instead of fighting it
//   iOS              the LaunchImage.imageset the template storyboard
//                    already centres (1x/2x/3x, Contents.json untouched),
//                    plus the storyboard's own background colour
//
// Same trade as fjs icon (whose resizer this reuses): no image library,
// in-place over the files `flutter create` left behind, nothing registered.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { flutterDir as configuredFlutterDir } from '../project/config.js';
import { findResizer, readPng, type Resizer } from './icon.js';

/** Launch-logo sizes per Android density bucket, from the --size dp. */
const ANDROID_DENSITIES: Array<[string, number]> = [
  ['drawable', 1],
  ['drawable-mdpi', 1],
  ['drawable-hdpi', 1.5],
  ['drawable-xhdpi', 2],
  ['drawable-xxhdpi', 3],
  ['drawable-xxxhdpi', 4],
];

interface SplashOptions {
  source: string;
  color?: string;
  size: number;
  platforms: Array<'android' | 'ios'>;
  dryRun: boolean;
}

export function splashCommand(argv: string[]): void {
  const opts = parseArgs(argv);
  const root = process.cwd();
  const source = path.resolve(root, opts.source);
  if (!fs.existsSync(source)) throw new Error(`no such file: ${opts.source}`);

  const image = readPng(source);
  if (image.width !== image.height) {
    console.warn(
      `warning: ${opts.source} is ${image.width}x${image.height}, not square — ` +
        'it will be squashed, not cropped',
    );
  }
  if (opts.color !== undefined && !/^#(?:[0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/i.test(opts.color)) {
    throw new Error(`--color wants #rgb / #rrggbb / #rrggbbaa, got ${opts.color}`);
  }

  const resizer = findResizer();
  const dir = path.resolve(root, configuredFlutterDir(root));
  if (!fs.existsSync(path.join(dir, 'pubspec.yaml'))) {
    throw new Error(
      `no Flutter host at ${path.relative(root, dir) || dir} — create it with fjs host create`,
    );
  }

  let written = 0;
  if (opts.platforms.includes('android')) {
    written += androidSplash(dir, resizer, source, opts, root);
  }
  if (opts.platforms.includes('ios')) {
    written += iosSplash(dir, resizer, source, opts, root);
  }

  if (written === 0) {
    console.log('nothing to write — is the Flutter host complete?');
    return;
  }
  console.log(`${opts.dryRun ? 'would write' : 'wrote'} ${written} files (via ${resizer.name})`);
  if (!opts.dryRun) {
    console.log(
      'rebuild the app to see it. on Android 12+ the system crops the splash ' +
        'icon to a circle at ~2/3 of the screen — leave transparent margins in the source',
    );
  }
}

// ------------------------------------------------------------------ android

function androidSplash(
  host: string,
  resizer: Resizer,
  source: string,
  opts: SplashOptions,
  root: string,
): number {
  const res = path.join(host, 'android', 'app', 'src', 'main', 'res');
  if (!fs.existsSync(path.join(res, 'values'))) return 0;
  let written = 0;

  for (const [dir, scale] of ANDROID_DENSITIES) {
    const out = path.join(res, dir, 'launch_image.png');
    const size = Math.round(opts.size * scale);
    written += emit(resizer, source, out, size, root, opts.dryRun);
  }

  // the colour comes from one @color both themes reference; without
  // --color the template default (white) stays
  if (opts.color !== undefined) {
    written += writeColorsXml(res, opts.color, root, opts.dryRun);
  }

  const colorRef = opts.color !== undefined ? '@color/launch_bg' : '@android:color/white';
  const layerList = [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by fjs splash: one colour + one centred launch image. -->',
    '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">',
    `    <item android:drawable="${colorRef}" />`,
    '    <item>',
    '        <bitmap',
    '            android:gravity="center"',
    '            android:src="@drawable/launch_image" />',
    '    </item>',
    '</layer-list>',
    '',
  ].join('\n');
  for (const dir of ['drawable', 'drawable-v21']) {
    const out = path.join(res, dir, 'launch_background.xml');
    if (!fs.existsSync(path.dirname(out))) continue;
    written += write(out, layerList, root, opts.dryRun);
  }

  written += v31Styles(res, opts, root);
  return written;
}

/** Creates (or patches) values-v31/styles.xml: the system splash attrs on
 * the LaunchTheme, on top of the same parents `values/styles.xml` declares. */
function v31Styles(res: string, opts: SplashOptions, root: string): number {
  const v31 = path.join(res, 'values-v31', 'styles.xml');
  if (!fs.existsSync(v31)) {
    const splashColor =
      opts.color !== undefined ? '@color/launch_bg' : '?android:colorBackground';
    const xml = [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<!-- Generated by fjs splash: the Android 12+ system splash. The icon',
      '     is masked to a circle by the OS at ~2/3 of the screen area. -->',
      '<resources>',
      '    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">',
      '        <item name="android:windowBackground">@drawable/launch_background</item>',
      `        <item name="android:windowSplashScreenBackground">${splashColor}</item>`,
      '        <item name="android:windowSplashScreenAnimatedIcon">@drawable/launch_image</item>',
      '    </style>',
      '    <style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar">',
      '        <item name="android:windowBackground">?android:colorBackground</item>',
      '    </style>',
      '</resources>',
      '',
    ].join('\n');
    return write(v31, xml, root, opts.dryRun);
  }

  // a host that already has v31 styles: point the two attrs at the launch
  // image / colour when missing or pointing elsewhere, leave the rest alone
  let xml = fs.readFileSync(v31, 'utf8');
  let touched = false;
  const splashColor = opts.color !== undefined ? '@color/launch_bg' : null;
  if (splashColor !== null) {
    const bgItem = `<item name="android:windowSplashScreenBackground">${splashColor}</item>`;
    if (xml.includes('windowSplashScreenBackground')) {
      if (!xml.includes(bgItem)) {
        xml = xml.replace(
          /<item name="android:windowSplashScreenBackground">[^<]*<\/item>/,
          bgItem,
        );
        touched = true;
      }
    } else {
      xml = intoLaunchTheme(xml, bgItem);
      touched = true;
    }
  }
  if (!xml.includes('windowSplashScreenAnimatedIcon')) {
    xml = intoLaunchTheme(xml, '<item name="android:windowSplashScreenAnimatedIcon">@drawable/launch_image</item>');
    touched = true;
  }
  if (!touched) return 0;
  return write(v31, xml, root, opts.dryRun);
}

/** Inserts one `<item>` line right after the LaunchTheme's opening tag. */
function intoLaunchTheme(xml: string, item: string): string {
  const theme = /(<style\s+name="LaunchTheme"[^>]*>)/.exec(xml);
  if (theme === null) {
    console.warn('warning: no LaunchTheme in values-v31/styles.xml — Android 12+ splash left as-is');
    return xml;
  }
  return xml.replace(theme[1], `${theme[1]}\n        ${item}`);
}

function writeColorsXml(res: string, color: string, root: string, dryRun: boolean): number {
  const file = path.join(res, 'values', 'colors.xml');
  const entry = `<color name="launch_bg">${color}</color>`;
  if (!fs.existsSync(file)) {
    return write(file, `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    ${entry}\n</resources>\n`, root, dryRun);
  }
  let xml = fs.readFileSync(file, 'utf8');
  if (xml.includes('name="launch_bg"')) {
    xml = xml.replace(/<color name="launch_bg">[^<]*<\/color>/, entry);
  } else {
    xml = xml.replace(/<\/resources>/, `    ${entry}\n</resources>`);
  }
  return write(file, xml, root, dryRun);
}

// ---------------------------------------------------------------------- ios

function iosSplash(
  host: string,
  resizer: Resizer,
  source: string,
  opts: SplashOptions,
  root: string,
): number {
  const runner = path.join(host, 'ios', 'Runner');
  let written = 0;

  const set = path.join(runner, 'Assets.xcassets', 'LaunchImage.imageset');
  if (fs.existsSync(set)) {
    // the template's Contents.json already lists the three scales
    written += emit(resizer, source, path.join(set, 'LaunchImage.png'), opts.size, root, opts.dryRun);
    written += emit(resizer, source, path.join(set, 'LaunchImage@2x.png'), opts.size * 2, root, opts.dryRun);
    written += emit(resizer, source, path.join(set, 'LaunchImage@3x.png'), opts.size * 3, root, opts.dryRun);
  } else if (opts.platforms.length === 1) {
    throw new Error(`no LaunchImage.imageset in ${path.relative(root, set)}`);
  }

  if (opts.color !== undefined) {
    written += storyboardColor(runner, opts.color, root, opts.dryRun);
  }
  return written;
}

/** Rewrites the storyboard's full-screen background colour. The template
 * carries exactly one `<color key="backgroundColor">` on the root view;
 * a storyboard shaped differently is left alone with a warning. */
function storyboardColor(runner: string, color: string, root: string, dryRun: boolean): number {
  const file = path.join(runner, 'Base.lproj', 'LaunchScreen.storyboard');
  if (!fs.existsSync(file)) {
    console.warn('warning: no LaunchScreen.storyboard — background colour not set');
    return 0;
  }
  const xml = fs.readFileSync(file, 'utf8');
  const lines = xml.split('\n');
  const hits = lines.reduce((n, line) => n + (line.includes('key="backgroundColor"') ? 1 : 0), 0);
  if (hits !== 1) {
    console.warn(
      `warning: LaunchScreen.storyboard has ${hits} backgroundColor lines (want 1) — ` +
        'background colour not set',
    );
    return 0;
  }
  const { r, g, b } = hexToRgb(color);
  const replaced = lines.map((line) =>
    line.includes('key="backgroundColor"')
      ? `                        <color key="backgroundColor" red="${r}" green="${g}" blue="${b}" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>`
      : line,
  );
  return write(file, `${replaced.join('\n')}\n`, root, dryRun);
}

/** colour → the 0–1 floats the storyboard XML uses. #rgb expands; an 8-digit
 * hex keeps its alpha out of this — the splash background is opaque. */
function hexToRgb(hex: string): { r: string; g: string; b: string } {
  let v = hex.slice(1);
  if (v.length === 3) v = [...v].map((c) => c + c).join('');
  if (v.length === 8) v = v.slice(0, 6); // alpha is not a splash concept here
  const n = parseInt(v, 16);
  const f = (x: number) => (Math.round(((n >> x) & 0xff) / 2.55) / 100).toFixed(2);
  return { r: f(16), g: f(8), b: f(0) };
}

// -------------------------------------------------------------------- shared

function emit(
  resizer: Resizer,
  source: string,
  out: string,
  size: number,
  root: string,
  dryRun: boolean,
): number {
  const shown = path.relative(root, out);
  if (dryRun) {
    console.log(`  ${shown}  ${size}x${size}`);
    return 1;
  }
  fs.mkdirSync(path.dirname(out), { recursive: true });
  const [cmd, args] = resizer.command(source, out, size);
  const result = spawnSync(cmd, args, { stdio: ['ignore', 'ignore', 'pipe'] });
  if (result.error || result.status !== 0) {
    throw new Error(
      `${resizer.name} failed on ${shown}:\n${result.stderr?.toString().trim() ?? result.error}`,
    );
  }
  console.log(`  ${shown}  ${size}x${size}`);
  return 1;
}

function write(file: string, content: string, root: string, dryRun: boolean): number {
  const shown = path.relative(root, file);
  if (dryRun) {
    console.log(`  ${shown}`);
    return 1;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log(`  ${shown}`);
  return 1;
}

function takeValue(argv: string[], i: number, flag: string): string {
  const value = argv[i];
  if (value === undefined) throw new Error(`${flag} takes a value`);
  return value;
}

function parseArgs(argv: string[]): SplashOptions {
  const opts: SplashOptions = { source: '', size: 192, platforms: ['android', 'ios'], dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--dry-run' || arg === '-n') opts.dryRun = true;
    else if (arg === '--color') opts.color = takeValue(argv, ++i, arg);
    else if (arg === '--size') opts.size = Number(takeValue(argv, ++i, arg));
    else if (arg === '--platform') {
      const value = takeValue(argv, ++i, arg);
      if (value !== 'android' && value !== 'ios') {
        throw new Error('--platform takes android or ios');
      }
      opts.platforms = [value];
    } else if (!arg.startsWith('-') && !opts.source) opts.source = arg;
    else throw new Error(`unknown splash option: ${arg}`);
  }
  if (!opts.source) throw new Error('fjs splash needs a source png: fjs splash logo.png --color #0a1a2f');
  if (!Number.isFinite(opts.size) || opts.size <= 0 || opts.size > 1024) {
    throw new Error('--size takes a logical px in 1..1024');
  }
  return opts;
}
