// generated by fjs autoimport — do not edit.
//
// Adapters binding the fjs.autoimport packages' public API to the object
// ABI (specs/159/160). Regenerated from .fjs/autoimport/*.api.json by
// `fjs autoimport` / `fjs run`; main.dart reaches this through
// fjsRegisterModules -> fjsRegisterObjects.
import 'package:flutter_fjs/flutter_fjs.dart';
import 'package:mmkv/mmkv.dart' as p0;

void fjsRegisterObjects(FjsEngine engine) {
  engine.objects.registerModule('mmkv', const _MmkvModule());
}

class _MmkvModule extends FjsObjectModule {
  const _MmkvModule();

  @override
  Object? construct(String className, List<Object?> args) {
    switch (className) {
      case 'MMBuffer':
        return p0.MMBuffer((args[0] as num).toInt());
      case 'MMKV':
        return p0.MMKV(args[0] as String, mode: (args.length > 1 ? args[1] : p0.MMKVMode.SINGLE_PROCESS_MODE) as p0.MMKVMode, cryptKey: (args.length > 2 ? args[2] : null) as String?, aes256: (args.length > 3 ? args[3] : false) as bool, rootDir: (args.length > 4 ? args[4] : null) as String?, expectedCapacity: ((args.length > 5 ? args[5] : 0) as num).toInt(), readOnly: (args.length > 6 ? args[6] : false) as bool, enableKeyExpire: (args.length > 7 ? args[7] : null) as bool?, expiredInSeconds: ((args.length > 8 ? args[8] : 0) as num).toInt(), enableCompareBeforeSet: (args.length > 9 ? args[9] : false) as bool, itemSizeLimit: ((args.length > 10 ? args[10] : 0) as num).toInt());
      case 'MMKVHandler':
        return p0.MMKVHandler();
      case 'NameSpace':
        return p0.NameSpace(args[0] as String);
      case 'initialize':
        return p0.MMKV.initialize(rootDir: (args.length > 0 ? args[0] : null) as String?, groupDir: (args.length > 1 ? args[1] : null) as String?);
      case 'nameSpace':
        return p0.MMKV.nameSpace(args[0] as String);
      case 'defaultNameSpace':
        return p0.MMKV.defaultNameSpace();
      case 'defaultMMKV':
        return p0.MMKV.defaultMMKV(cryptKey: (args.length > 0 ? args[0] : null) as String?, aes256: (args.length > 1 ? args[1] : false) as bool, expectedCapacity: ((args.length > 2 ? args[2] : 0) as num).toInt(), enableKeyExpire: (args.length > 3 ? args[3] : null) as bool?, expiredInSeconds: ((args.length > 4 ? args[4] : 0) as num).toInt(), enableCompareBeforeSet: (args.length > 5 ? args[5] : false) as bool, itemSizeLimit: ((args.length > 6 ? args[6] : 0) as num).toInt());
      case 'backupOneToDirectory':
        return p0.MMKV.backupOneToDirectory(args[0] as String, args[1] as String, rootDir: (args.length > 2 ? args[2] : null) as String?);
      case 'restoreOneMMKVFromDirectory':
        return p0.MMKV.restoreOneMMKVFromDirectory(args[0] as String, args[1] as String, rootDir: (args.length > 2 ? args[2] : null) as String?);
      case 'backupAllToDirectory':
        return p0.MMKV.backupAllToDirectory(args[0] as String);
      case 'restoreAllFromDirectory':
        return p0.MMKV.restoreAllFromDirectory(args[0] as String);
      case 'isFileValid':
        return p0.MMKV.isFileValid(args[0] as String, rootDir: (args.length > 1 ? args[1] : null) as String?);
      case 'removeStorage':
        return p0.MMKV.removeStorage(args[0] as String, rootDir: (args.length > 1 ? args[1] : null) as String?);
      case 'checkExist':
        return p0.MMKV.checkExist(args[0] as String, rootDir: (args.length > 1 ? args[1] : null) as String?);
      case 'groupPath':
        return p0.MMKV.groupPath();
    }
    throw StateError('mmkv has no binding "$className" (not generated — see fjs autoimport output)');
  }
  @override
  Object? invoke(Object instance, String member, List<Object?> args) {
    switch (instance) {
      case p0.MMBuffer self:
        switch (member) {
          case 'destroy':
            self.destroy();
            return null;
          case 'length':
            return self.length;
          case 'isFromNative':
            return self.isFromNative;
        }
      case p0.MMKV self:
        switch (member) {
          case 'encodeBool':
            return self.encodeBool(args[0] as String, args[1] as bool, ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeBool':
            return self.decodeBool(args[0] as String, defaultValue: (args.length > 1 ? args[1] : false) as bool);
          case 'encodeInt32':
            return self.encodeInt32(args[0] as String, (args[1] as num).toInt(), ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeInt32':
            return self.decodeInt32(args[0] as String, defaultValue: ((args.length > 1 ? args[1] : 0) as num).toInt());
          case 'encodeInt':
            return self.encodeInt(args[0] as String, (args[1] as num).toInt(), ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeInt':
            return self.decodeInt(args[0] as String, defaultValue: ((args.length > 1 ? args[1] : 0) as num).toInt());
          case 'encodeDouble':
            return self.encodeDouble(args[0] as String, (args[1] as num).toDouble(), ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeDouble':
            return self.decodeDouble(args[0] as String, defaultValue: ((args.length > 1 ? args[1] : 0) as num).toDouble());
          case 'encodeString':
            return self.encodeString(args[0] as String, args[1] as String?, ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeString':
            return self.decodeString(args[0] as String);
          case 'encodeBytes':
            return self.encodeBytes(args[0] as String, args[1] as p0.MMBuffer?, ((args.length > 2 ? args[2] : null) as num?)?.toInt());
          case 'decodeBytes':
            return self.decodeBytes(args[0] as String);
          case 'reKey':
            return self.reKey(args[0] as String?, aes256: (args.length > 1 ? args[1] : false) as bool);
          case 'checkReSetCryptKey':
            self.checkReSetCryptKey(args[0] as String, aes256: (args.length > 1 ? args[1] : false) as bool);
            return null;
          case 'valueSize':
            return self.valueSize(args[0] as String, args[1] as bool);
          case 'writeValueToNativeBuffer':
            return self.writeValueToNativeBuffer(args[0] as String, args[1] as p0.MMBuffer);
          case 'containsKey':
            return self.containsKey(args[0] as String);
          case 'removeValue':
            self.removeValue(args[0] as String);
            return null;
          case 'clearAll':
            self.clearAll(keepSpace: (args.length > 0 ? args[0] : false) as bool);
            return null;
          case 'sync':
            self.sync(args[0] as bool);
            return null;
          case 'clearMemoryCache':
            self.clearMemoryCache();
            return null;
          case 'trim':
            self.trim();
            return null;
          case 'importFrom':
            return self.importFrom(args[0] as p0.MMKV);
          case 'close':
            self.close();
            return null;
          case 'enableAutoKeyExpire':
            return self.enableAutoKeyExpire((args[0] as num).toInt());
          case 'disableAutoKeyExpire':
            return self.disableAutoKeyExpire();
          case 'enableCompareBeforeSet':
            return self.enableCompareBeforeSet();
          case 'disableCompareBeforeSet':
            return self.disableCompareBeforeSet();
          case 'checkContentChangedByOuterProcess':
            self.checkContentChangedByOuterProcess();
            return null;
          case 'mmapID':
            return self.mmapID;
          case 'cryptKey':
            return self.cryptKey;
          case 'allKeys':
            return self.allKeys;
          case 'allNonExpiredKeys':
            return self.allNonExpiredKeys;
          case 'count':
            return self.count;
          case 'countNonExpiredKeys':
            return self.countNonExpiredKeys;
          case 'totalSize':
            return self.totalSize;
          case 'actualSize':
            return self.actualSize;
          case 'isMultiProcess':
            return self.isMultiProcess;
          case 'isReadOnly':
            return self.isReadOnly;
        }
      case p0.MMKVHandler self:
        switch (member) {
          case 'wantLogRedirect':
            return self.wantLogRedirect();
          case 'wantContentChangeNotification':
            return self.wantContentChangeNotification();
          case 'onContentChangedByOuterProcess':
            self.onContentChangedByOuterProcess(args[0] as String);
            return null;
          case 'onMMKVContentLoadSuccessfully':
            self.onMMKVContentLoadSuccessfully(args[0] as String);
            return null;
        }
      case p0.NameSpace self:
        switch (member) {
          case 'mmkv':
            return self.mmkv(args[0] as String, mode: (args.length > 1 ? args[1] : p0.MMKVMode.SINGLE_PROCESS_MODE) as p0.MMKVMode, cryptKey: (args.length > 2 ? args[2] : null) as String?, aes256: (args.length > 3 ? args[3] : false) as bool, expectedCapacity: ((args.length > 4 ? args[4] : 0) as num).toInt(), readOnly: (args.length > 5 ? args[5] : false) as bool, enableKeyExpire: (args.length > 6 ? args[6] : null) as bool?, expiredInSeconds: ((args.length > 7 ? args[7] : 0) as num).toInt(), enableCompareBeforeSet: (args.length > 8 ? args[8] : false) as bool, itemSizeLimit: ((args.length > 9 ? args[9] : 0) as num).toInt());
          case 'backupOneToDirectory':
            return self.backupOneToDirectory(args[0] as String, args[1] as String);
          case 'restoreOneMMKVFromDirectory':
            return self.restoreOneMMKVFromDirectory(args[0] as String, args[1] as String);
          case 'isFileValid':
            return self.isFileValid(args[0] as String);
          case 'removeStorage':
            return self.removeStorage(args[0] as String);
          case 'checkExist':
            return self.checkExist(args[0] as String);
          case 'rootDir':
            return self.rootDir;
        }
    }
    throw StateError('mmkv: no binding "$member" (not generated — see fjs autoimport output)');
  }

  @override
  Object? get(Object instance, String member) {
    switch (instance) {
      case p0.MMBuffer self:
        switch (member) {
          case 'length':
            return self.length;
          case 'isFromNative':
            return self.isFromNative;
        }
      case p0.MMKV self:
        switch (member) {
          case 'mmapID':
            return self.mmapID;
          case 'cryptKey':
            return self.cryptKey;
          case 'allKeys':
            return self.allKeys;
          case 'allNonExpiredKeys':
            return self.allNonExpiredKeys;
          case 'count':
            return self.count;
          case 'countNonExpiredKeys':
            return self.countNonExpiredKeys;
          case 'totalSize':
            return self.totalSize;
          case 'actualSize':
            return self.actualSize;
          case 'isMultiProcess':
            return self.isMultiProcess;
          case 'isReadOnly':
            return self.isReadOnly;
        }
      case p0.NameSpace self:
        switch (member) {
          case 'rootDir':
            return self.rootDir;
        }
    }
    return FjsMethod.instance;
  }
}
