# Writes the version script that decides what libfjs.so exports (spec 116).
#
#   cmake -DOUT=<map> [-DNM=<nm> -DOBJECTS_FILE=<list>] -P libfjs-exports.cmake
#
# libfjs.so exports the fjs_* C ABI (Dart FFI's only entry points) plus every
# symbol the pluggable debugger module references — read here from the
# module's own object files, so the list is exact for the ABI being built and
# cannot drift from the code. A committed list could not work: C++ mangling
# differs per ABI (size_t is `m` on arm64 but `j` on armv7).
#
# The module's undefined symbols include libc/liblog names libfjs does not
# define; listing them is harmless (the link passes --undefined-version) and
# they are not exported. They also include libc++ symbols libfjs DOES define:
# those stay exported on purpose — the module shares the engine's copy of
# libc++ today, and hiding them would make the linker quietly pull a second
# copy from libc++_static into the module.
#
# Without OBJECTS_FILE (no debugger module: quickjs, or FJS_DEBUGGER=OFF)
# only fjs_* is exported.

if(NOT OUT)
    message(FATAL_ERROR "libfjs-exports.cmake: OUT is required")
endif()

set(symbols "")
if(OBJECTS_FILE)
    file(STRINGS "${OBJECTS_FILE}" objects)
    if(NOT objects)
        message(FATAL_ERROR "libfjs-exports.cmake: no debugger objects listed in ${OBJECTS_FILE}")
    endif()
    execute_process(
        COMMAND "${NM}" --undefined-only ${objects}
        OUTPUT_VARIABLE listing
        ERROR_VARIABLE errors
        RESULT_VARIABLE status)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "libfjs-exports.cmake: ${NM} failed (${status}): ${errors}")
    endif()
    string(REPLACE "\n" ";" lines "${listing}")
    foreach(line IN LISTS lines)
        # "                 U name" (object-file headers and blanks never match)
        if(line MATCHES "^[ \t]*U[ \t]+([^ \t]+)$")
            set(name "${CMAKE_MATCH_1}")
            # fjs_* is exported by the wildcard already
            if(NOT name MATCHES "^fjs_")
                list(APPEND symbols "${name}")
            endif()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES symbols)
    list(SORT symbols)
    list(LENGTH symbols count)
    if(count EQUAL 0)
        message(FATAL_ERROR "libfjs-exports.cmake: the debugger objects reference nothing — wrong object list?")
    endif()
endif()

set(body "/* generated by native/cmake/libfjs-exports.cmake (spec 116) — do not edit */\n{\n  global:\n    fjs_*;\n")
foreach(name IN LISTS symbols)
    string(APPEND body "    \"${name}\";\n")
endforeach()
string(APPEND body "  local:\n    *;\n};\n")

# rewrite only on change, so an unchanged debugger does not relink libfjs
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL body)
    file(WRITE "${OUT}" "${body}")
endif()
