// generated by fjs autoimport — do not edit.
//
// Types for the fjs.autoimport packages, merged into dartModule's key
// lookup (specs/160). Regenerated from .fjs/autoimport/*.api.json.

declare module '@ufjs/runtime' {
  interface FjsObjectModules {
    mmkv: MmkvModule;
  }
}

export interface MMBuffer {
  readonly length: number;
  readonly isFromNative: boolean;
  destroy(): void;
}

export interface MMBufferCtor {
  (length: number): MMBuffer;
}

export interface MMKV {
  readonly mmapID: string;
  readonly cryptKey: string | null;
  readonly allKeys: Array<string>;
  readonly allNonExpiredKeys: Array<string>;
  readonly count: number;
  readonly countNonExpiredKeys: number;
  readonly totalSize: number;
  readonly actualSize: number;
  readonly isMultiProcess: boolean;
  readonly isReadOnly: boolean;
  encodeBool(key: string, value: boolean, expireDurationInSecond?: number | null): boolean;
  decodeBool(key: string, defaultValue?: boolean): boolean;
  encodeInt32(key: string, value: number, expireDurationInSecond?: number | null): boolean;
  decodeInt32(key: string, defaultValue?: number): number;
  encodeInt(key: string, value: number, expireDurationInSecond?: number | null): boolean;
  decodeInt(key: string, defaultValue?: number): number;
  encodeDouble(key: string, value: number, expireDurationInSecond?: number | null): boolean;
  decodeDouble(key: string, defaultValue?: number): number;
  encodeString(key: string, value: string | null, expireDurationInSecond?: number | null): boolean;
  decodeString(key: string): string | null;
  encodeBytes(key: string, value: MMBuffer | null, expireDurationInSecond?: number | null): boolean;
  decodeBytes(key: string): MMBuffer | null;
  reKey(cryptKey: string | null, aes256?: boolean): boolean;
  checkReSetCryptKey(cryptKey: string, aes256?: boolean): void;
  valueSize(key: string, actualSize: boolean): number;
  writeValueToNativeBuffer(key: string, buffer: MMBuffer): number;
  containsKey(key: string): boolean;
  removeValue(key: string): void;
  clearAll(keepSpace?: boolean): void;
  sync(sync: boolean): void;
  clearMemoryCache(): void;
  trim(): void;
  importFrom(src: MMKV): number;
  close(): void;
  enableAutoKeyExpire(expiredInSeconds: number): boolean;
  disableAutoKeyExpire(): boolean;
  enableCompareBeforeSet(): boolean;
  disableCompareBeforeSet(): boolean;
  checkContentChangedByOuterProcess(): void;
}

export interface MMKVCtor {
  (mmapID: string, mode?: MMKVMode, cryptKey?: string | null, aes256?: boolean, rootDir?: string | null, expectedCapacity?: number, readOnly?: boolean, enableKeyExpire?: boolean | null, expiredInSeconds?: number, enableCompareBeforeSet?: boolean, itemSizeLimit?: number): MMKV;
}

export interface MMKVHandler {
  wantLogRedirect(): boolean;
  wantContentChangeNotification(): boolean;
  onContentChangedByOuterProcess(mmapID: string): void;
  onMMKVContentLoadSuccessfully(mmapID: string): void;
}

export interface MMKVHandlerCtor {
  (): MMKVHandler;
}

export interface NameSpace {
  readonly rootDir: string;
  mmkv(mmapID: string, mode?: MMKVMode, cryptKey?: string | null, aes256?: boolean, expectedCapacity?: number, readOnly?: boolean, enableKeyExpire?: boolean | null, expiredInSeconds?: number, enableCompareBeforeSet?: boolean, itemSizeLimit?: number): MMKV;
  backupOneToDirectory(mmapID: string, dstDir: string): boolean;
  restoreOneMMKVFromDirectory(mmapID: string, srcDir: string): boolean;
  isFileValid(mmapID: string): boolean;
  removeStorage(mmapID: string): boolean;
  checkExist(mmapID: string): boolean;
}

export interface NameSpaceCtor {
  (dir: string): NameSpace;
}

export interface MmkvModule {
  MMBuffer: MMBufferCtor;
  MMKV: MMKVCtor;
  MMKVHandler: MMKVHandlerCtor;
  NameSpace: NameSpaceCtor;
  initialize(rootDir?: string | null, groupDir?: string | null): Promise<string>;
  nameSpace(path: string): NameSpace;
  defaultNameSpace(): NameSpace;
  defaultMMKV(cryptKey?: string | null, aes256?: boolean, expectedCapacity?: number, enableKeyExpire?: boolean | null, expiredInSeconds?: number, enableCompareBeforeSet?: boolean, itemSizeLimit?: number): MMKV;
  backupOneToDirectory(mmapID: string, dstDir: string, rootDir?: string | null): boolean;
  restoreOneMMKVFromDirectory(mmapID: string, srcDir: string, rootDir?: string | null): boolean;
  backupAllToDirectory(dstDir: string): number;
  restoreAllFromDirectory(srcDir: string): number;
  isFileValid(mmapID: string, rootDir?: string | null): boolean;
  removeStorage(mmapID: string, rootDir?: string | null): boolean;
  checkExist(mmapID: string, rootDir?: string | null): boolean;
  groupPath(): string | null;
}
